

<?php 

	$Mclt = array
	(
		array(
			"sl",						// 0 indentificador
			"Sala",						// 1 setor
			"Controle da Iluminação",			// 2 titulo do ccontrole
			"sl.jpg",					// 3 imagem que está em "./img"
			"Foto de uma sala"),				// 4 alt da imagem
			

		array(
			"cz",
			"Cozinha",
			"Controle da Iluminação",
			"cz.jpg",
			"Foto de uma Cozinha"),

		array(
			"qt",
			"Quarto",
			"Controle da Iluminação",
			"qt.jpg",
			"Foto de uma quarto"),

		array(
			"bh",
			"Banheiro",
			"Controle do Aquecimento",
			"bh.jpg",
			"Foto de uma Banheiro"),

		array(
			"jd",
			"Jardin",
			"Controle da Irrigação",
			"jd.jpg",
			"Foto de uma Jardin")
	); 
?>
